# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [master]

jobs:
- install: npm install, build, and test
      run: |
        npm i
        npm run build --if-present
- depoly: Deploy
      uses: peaceiris/actions-gh-pages@v2.5.0
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACCESS-TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: dist